image: ubuntu

stack: node 12

test: off

build_script:
- yarn

deploy_script:
- git config --global user.name "${GH_NAME}"
- git config --global user.email "${GH_EMAIL}"
- echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
- GIT_USER="${GH_NAME}" yarn deploy